### ISSUE TITLE
Stuck on Redeeming your Monero

### ISSUE THREAD

**Issue by saint317** [UnstoppableSwap/unstoppableswap-gui#162]
Converting about 0.009BTC to XMR, and it's taking over an hour to redeem my XMR. The other party has redeemed my BTC. It says the redeeming should take about 2 minutes, it's been over an hour. What's going on? How do I fix it? Thanks. 

Version 0.5.2, used the second transfer option with 99% uptime.

**Comment by binarybaron** [comment]
Hey,
I apologize for the issue you are facing. We are working on a fix for that as we speak. Your funds are completely safe. They are inside of a Monero wallet only you have the keys to. There is no time pressure and I'll help you redeem your funds.
This is caused by an issue with the communication with the Monero wallet.
You'll have to use the `monero-recovery` command to print the keys for the internal Monero wallet, open that wallet in the Monero Wallet GUI and transfer the funds manually.

Assuming you are on windows, you need to do the following to retrieve your funds.

1. Download and extract the `swap` tool from https://github.com/comit-network/xmr-btc-swap/releases/tag/0.12.1 to your desktop
2. Open PowerShell
3. Navigate to the desktop: `cd Desktop`
4. Execute the following command. Replace `SWAP_ID` with the ID of your swap: `./swap --data-base-dir C:\Users\YOUR_USERNAME\AppData\Roaming\xmr-btc-swap\cli monero-recovery --swap-id SWAP_ID`
5. Use the printed Wallet Address, View Key and Spend Key to create a wallet in Monero Wallet GUI. Set the restore height to a few days before your swap. Let the wallet scan the blockchain and then send the funds to the desired wallet

Let me know if you encounter any problems or need any help with the process. I apologise for the inconvenience, we are still trying to figure out the root cause of this.

**Comment by binarybaron** [comment]
Also, after you manage to redeem the funds. Please post the logs of your swap (History - > Expand -> View Logs) to help us debug this issue.

**Comment by binarybaron** [comment]
Did you manage to redeem the funds? @saint317

**Comment by saint317** [comment]
Hi, yes I managed to get them. It just took a while (>2 hours) when it said
2 minutes so I was getting worried. All is solved now though thank you.
