### ISSUE TITLE
Daemon unexpectedly stopped

### ISSUE THREAD

**Issue by Spyx34** [UnstoppableSwap/unstoppableswap-gui#224]
## Explain what you did

I started a swap, and midst btc transaction confirmation lost connection bc of poweroutage, after some time laptop went dark as well, recharged it and reconnected after few hours. Swap wouldnt complete even if btc transaction was confirmed.
Restarted the app now it wont connect anymore.
Also had someproblems with antivirus, if that might be related(uninstalled avira now)

## Which state is your swap in?

History won't load
## What is the problem?

It doesnt show my swap anymore neither did any coins show up

Swap Daemon Logs:
  {"timestamp":"2024-09-30T19:37:58.0019821Z","level":"INFO","fields":{"message":"Logging initialized to C:\\Users\\wenze\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\logs"}}
{"timestamp":"2024-09-30T19:37:58.0022488Z","level":"DEBUG","fields":{"message":"Reading in seed from C:\\Users\\wenze\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\seed.pem"}}
{"timestamp":"2024-09-30T19:38:01.0560294Z","level":"DEBUG","fields":{"message":"RPC exec path: C:\\Users\\wenze\\AppData\\Roaming\\xmr-btc-swap\\cli\\mainnet\\monero\\monero-wallet-rpc.exe"}}
"Error: Access is denied. (os error 5)"

## Your Environment

- Operating System:
 Windwos 11
- GUI Version:
 0.6.3

**Comment by symb10sis** [comment]
I had the same issue on Windows 11 running Version 0.6.4. The daemon wouldn't start even if I reinstalled Unstoppable GUI.
The problem was that Windows Defender marked monero-wallet-rpc.exe as a potential unwanted app and thus blocked it from running.

What I did to solve the problem for me was going to the Windows 11 **Settings --> Privacy & security --> Virus & threat protection -->Protection history** here I saw that C:\Users\[YOUR-USERNAME]\AppData\Roaming\xmr-btc-swap\cli\mainnet\monero\monero-wallet-rpc.exe was blocked. I clicked on one of the events and chose to allow it.

Hope this helps

**Comment by binarybaron** [comment]
> I had the same issue on Windows 11 running Version 0.6.4. The daemon wouldn't start even if I reinstalled Unstoppable GUI.
> 
> The problem was that Windows Defender marked monero-wallet-rpc.exe as a potential unwanted app and thus blocked it from running.
> 
> 
> 
> What I did to solve the problem for me was going to the Windows 11 **Settings --> Privacy & security --> Virus & threat protection -->Protection history** here I saw that C:\Users\[YOUR-USERNAME]\AppData\Roaming\xmr-btc-swap\cli\mainnet\monero\monero-wallet-rpc.exe was blocked. I clicked on one of the events and chose to allow it.
> 
> 
> 
> Hope this helps

This is the solution.
